// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6V57TTgqamILHaFDUghKEHe-m3cRjUVo',
    appId: '1:326957471563:web:e92249f8c8887e4ac0bace',
    messagingSenderId: '326957471563',
    projectId: 'lolapp-8c028',
    authDomain: 'lolapp-8c028.firebaseapp.com',
    storageBucket: 'lolapp-8c028.appspot.com',
    measurementId: 'G-5J52TYWC8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfdKFRKe4YCmZR-1VvXck8EsWcQ9xoMKk',
    appId: '1:422361141696:android:9911b2b355864d5dbbf825',
    messagingSenderId: '422361141696',
    projectId: 'stone-dapp-4142a',
    storageBucket: 'stone-dapp-4142a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7UCtaejhq8mRJOtb8T_PsJlzQmnBO0eU',
    appId: '1:422361141696:ios:e8a1db9340916188bbf825',
    messagingSenderId: '422361141696',
    projectId: 'stone-dapp-4142a',
    storageBucket: 'stone-dapp-4142a.appspot.com',
    iosBundleId: 'ladans.io.lol.app',
  );

}